/**
 * Standardized SITS Alert severity, status, channel, and types.
 */
import { IfsEventType } from "../ifs/enums/ifs-event.enum.js";

export enum AlertSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  CRITICAL = "CRITICAL",
}

export enum AlertStatus {
  OPEN = "OPEN",
  ACKNOWLEDGED = "ACKNOWLEDGED",
  RESOLVED = "RESOLVED",
}

export enum AlertChannel {
  IN_APP = "in-app",
}

export enum AlertType {
  GENERAL = "GENERAL",
  TRANSIT_EXIT_NOT_APPROVED = "TRANSIT_EXIT_NOT_APPROVED",
  GATE_ALARM = "GATE_ALARM",
  UNAPPROVED_TAG_DETECTED = "UNAPPROVED_TAG_DETECTED",
  COUNT_VARIANCE = "COUNT_VARIANCE",
  COUNT_MISMATCH = "COUNT_MISMATCH",
  LINE_COUNT_VARIANCE = "LINE_COUNT_VARIANCE",
  BASELINE_VARIANCE = "BASELINE_VARIANCE",
  HOLDING_MISSING = "HOLDING_MISSING",
  HOLDING_EXTRA = "HOLDING_EXTRA",
  PLACEMENT_MISMATCH = "PLACEMENT_MISMATCH",
  SYNC_CONFLICT = "SYNC_CONFLICT",
  STOCK_VERIFICATION_VARIANCE = "STOCK_VERIFICATION_VARIANCE",
  WRONG_BIN_PLACEMENT = "WRONG_BIN_PLACEMENT",
  COUNT_CHECK_VARIANCE = "COUNT_CHECK_VARIANCE",
  HOLDING_SHORTFALL = "HOLDING_SHORTFALL",
  STOCK_VERIFICATION_DISCREPANCY = "stock-verification.discrepancy",
  TRANSIT_DOOR_UNAUTHORIZED = "TRANSIT_DOOR_UNAUTHORIZED",
  GATE_UNAUTHORIZED_EXIT = "GATE_UNAUTHORIZED_EXIT",
  HOLDING_SHORT_RECEIPT = "HOLDING_SHORT_RECEIPT",
  IFS_WATERMARK_ERROR = "ifs.watermark.error",
  IFS_REPOLL_FAILED = "ifs.repoll.failed",
  RR_LINE_SERIALS_MISSING = IfsEventType.RR_LINE_SERIALS_MISSING,
  GATE_ENTRY_LINE_FLAGGED = IfsEventType.GATE_ENTRY_LINE_FLAGGED,
}
